### ISSUE TITLE
Admin - Inner banner section: Should be better to implement as a gallery ACF for every page instead of inner banner custom post.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Hutton---Northey-Sales#36]
and also there's no inner banner section mentioned in scope.

![untitled-1innerb](https://cloud.githubusercontent.com/assets/13309730/12416377/2810e448-bec7-11e5-9ca8-1f6b71729170.png)

**Comment by mahender-sowedane** [comment]
Not fixed

**Comment by isaq-titan** [comment]
Hi, It was not inner banner, it is just a featured image as mentioned in scope and I have updated the same.

![hutton northey sales - google sheets 2016-02-03 18-42-32](https://cloud.githubusercontent.com/assets/13450822/12783194/fafa673c-caa5-11e5-87a1-14f1229ee8f6.png)

**Comment by mahender-sowedane** [comment]
Then what about provided design, have a look below psd.
Update the scope or Discuss with your TL and fix it properly.
thanks!

![2016-02-04_0928-psd](https://cloud.githubusercontent.com/assets/13309730/12805603/034dc8d4-cb23-11e5-9bb7-91b34627c12f.png)
