### ISSUE TITLE
Header: Log-in button is cut when re-sized at 768 resolution.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#59]
![image](https://cloud.githubusercontent.com/assets/11186313/13037977/08143540-d3c7-11e5-89d4-ae09bfce0b01.png)

**Comment by mahender-sowedane** [comment]
Not fixed properly

![2016-02-20_1258-321-issue59](https://cloud.githubusercontent.com/assets/13309730/13209323/a27282d2-d948-11e5-8497-a4ca1ffdb72f.png)
