### ISSUE TITLE
Home: Featured image on collapsed view is placed at the far left if paragraph contains shorter text leaving too much space gap at the center. And in expanded view, there is white space gap at the top and button of the image.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#61]
![image](https://cloud.githubusercontent.com/assets/11186313/13038992/0e2476f8-d3d5-11e5-9773-d5bf6a5f311c.png)
![image](https://cloud.githubusercontent.com/assets/11186313/13038996/126b7bbc-d3d5-11e5-9546-916d39194843.png)

**Comment by kabirkhan123** [comment]
Content section has not implemented properly have to re-design this section. Let me know if you expecting content section should be like in bellow reference site. 
http://netpack.stage.titanweb.com.au/

Thanks

**Comment by mahender-sowedane** [comment]
It's bug needs to be fixed, Discuss with your TL and fix it properly.
thanks!

**Comment by roseliesromeo** [comment]
Still not fixed...Design layout is not achieved on collapsed view.
