### ISSUE TITLE
Pre-footer: Style of the pre-footer logo doesn't match the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#62]
![image](https://cloud.githubusercontent.com/assets/11186313/13039263/b16b57c6-d3d7-11e5-8f51-152a67ae25a7.png)

**Comment by kabirkhan123** [comment]
As per footer.psd file the footer logo is in white color and we are following the same.

**Comment by mahender-sowedane** [comment]
The Homepage PSD is more updated than the footer PSD and should be followed.
Also, It seems like both are little different. have a look below screen.
Bcoz as per design home page psd footer logo title should be uppercase and footer logo title should be capitalized.
thanks!

![pre-ftr](https://cloud.githubusercontent.com/assets/13309730/13217302/88355c52-d987-11e5-8b58-e0fa92baedee.png)
