### ISSUE TITLE
Pre footer: It is using different color for the RSS feed compared to the given design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#66]
![image](https://cloud.githubusercontent.com/assets/11186313/13040616/7a7bd2a6-d3e9-11e5-9e6d-0d191f6d89c6.png)

**Comment by mahender-sowedane** [comment]
Not fixed.
Social links icon's section not implemented as per design, It must be used font-awesome icons instead of images.

![2016-02-22_0935-issue66](https://cloud.githubusercontent.com/assets/13309730/13209238/a6922300-d947-11e5-90bc-acce6e4116a1.png)
