### ISSUE TITLE
Used Machinery: Clipped text in the post title is still visible.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#69]
![image](https://cloud.githubusercontent.com/assets/11186313/13042533/ca59224e-d3fb-11e5-9ff4-5e3d14077576.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-02-20_1139-69issue](https://cloud.githubusercontent.com/assets/13309730/13209186/1667827a-d947-11e5-8d14-220989afd89b.png)
