### ISSUE TITLE
Used machinery: Distorted grid layout.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#70]
![image](https://cloud.githubusercontent.com/assets/11186313/13042773/c66aa1f6-d3fd-11e5-8fe4-6e2a966239a6.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-02-22_0924-issue70](https://cloud.githubusercontent.com/assets/13309730/13209143/8a909b6a-d946-11e5-899b-cde983400bcb.png)
