### ISSUE TITLE
Used machinery: Not all posts are displayed in front end. Created 13 posts for Used machinery but only 10 are displayed; those without featured image aren't.  View more button isn't displayed as well. 

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#71]
![image](https://cloud.githubusercontent.com/assets/11186313/13043047/80464e52-d400-11e5-8960-e226cf660918.png)
![image](https://cloud.githubusercontent.com/assets/11186313/13043054/830e8c9e-d400-11e5-8f9f-10fbebaccaa5.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-02-22_0924-issue70](https://cloud.githubusercontent.com/assets/13309730/13209125/2d6155b0-d946-11e5-81bd-bbbdb11fb6d6.png)
