### ISSUE TITLE
Sidebar: Clipped post title.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#72]
![image](https://cloud.githubusercontent.com/assets/11186313/13043334/7b40a9c8-d402-11e5-8fed-00f75a117d04.png)

**Comment by mahender-sowedane** [comment]
Not fixed, Still affected on devices.

![img_1441](https://cloud.githubusercontent.com/assets/13309730/13209073/943d0f82-d945-11e5-8c13-8c23ba736246.PNG)
