### ISSUE TITLE
Header: It will look better if the phone numbers lines up below the logos while the logos are occupy the first line.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hutton---Northey-Sales#80]
![image](https://cloud.githubusercontent.com/assets/11186313/13044069/228f60b2-d407-11e5-8624-4c320b27b7b0.png)

**Comment by mahender-sowedane** [comment]
Not fixed, still text breaks to the next line on certain resolutions.

![2016-02-20_1000-header](https://cloud.githubusercontent.com/assets/13309730/13208799/82a54b7a-d942-11e5-951c-d89435545e6c.png)
